### PR TITLE
update version to 1.3.0

### PR DESCRIPTION
**Pull request by oiseauroch**

### CODE REVIEW

**Comment by oiseauroch** [comment]
!testme

**Comment by alexAubin** [comment]
Sounds like it's crashing with a 502 : 

```
petrolette[4552]: Error: Cannot find module '/opt/yunohost/petrolette/routes/../../favrat/'
```

Does that mean anything to you ?

**Comment by oiseauroch** [comment]
!testme

**Comment by oiseauroch** [comment]
!testme

**Comment by oiseauroch** [comment]
!testme

**Comment by oiseauroch** [comment]
!testme

**Comment by oiseauroch** [comment]
!testme

**Pull request merged**
